refactor(governance): rename "api" to "method"
Agoric/agoric-sdk pull request #4980
Opened 2022-03-31 13:39 UTC by turadg

Follow up to #4868 

## Description

What are called `governedApis` are a set of methods that contribute to the API of the contract, not each a new API in itself. This renames those to `governedMethods` and the `voteOnApiInvocation` to `voteOnMethodInvocation`.

You can see from commit history I tried the more concise `voteOnInvocation` but it lost the symmetry with `voteOnParamChange` (vote on noun action).

### Security Considerations

--

### Documentation Considerations

Docs updated in global replace. Docs outside this repo not written yet.

### Testing Considerations

--

2022-03-31 16:20 UTC, Chris-Hibbert commented
I'm not completely happy with `voteOnMethodInvocation`, not that I have a better proposal right now.

Part of the design is that the methods to be invoked are segregated into a separate facet, to emphasize that the mechanism can't invoke arbitrary methods of the contract. In this sense, the methods accessible to governance form an API or a particular collection of methods.

2022-03-31 16:37 UTC, Chris-Hibbert requested changes
The usages that have been corrected to "method" don't grate on me as much as I expected, but unless we have a rule of thumb about what aspect of the mechanism it makes sense to refer to as "API", I think more renaming is in order. We still refer to API governance, and API questions, etc.


Find and replace many more usages of API for consistency.

rename `governApi.js`.
also search for "ApiGovernance", "invokeApi", "governApi", "governedApi", and "ApiQuestion".
Many things in `question.js` have inconsistent terminology, including the enum `API_INVOCATION`, and `assertApiInvocation`.

2022-03-31 16:37 UTC, Chris-Hibbert commented on packages/governance/src/contractGovernor.js
> +    // @ts-ignore `governedMethods` is present on contracts wiht API invocation.
```suggestion
    // @ts-ignore `governedMethods` is present on contracts that support method invocation.
```

2022-03-31 16:37 UTC, Chris-Hibbert commented on packages/governance/src/contractGovernor.js
> +    // if we aren't governing APIs, voteOnMethodInvocation shouldn't be called
```suggestion
    // if we don't support method invocation, voteOnMethodInvocation shouldn't be called
```

2022-03-31 16:37 UTC, Chris-Hibbert commented on packages/governance/src/contractHelper.js
>        // The contract provides a facet with the APIs that can be invoked by
```suggestion
      // The contract provides a facet with the methods that can be invoked by
```

2026-06-08 18:31 UTC, turadg commented
Contract governance is mothballed

2026-06-08 18:31 UTC, closed without merging